version: '3'
services:
  api:
    build:
      context: ./recipes_api
      args:
        JAR_FILE_LOCATION: ./target/recipes_api-1.0-SNAPSHOT.jar
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "8080:8080"
  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
    links:
      - api:recipe-api
