version: '3'

services:

  api:
    build:
      context: ./recipes_api
      args:
        JAR_FILE_LOCATION: ./target/recipes_api-1.0-SNAPSHOT.jar
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "8080:8080"

  prometheus:
    build: ./prometheus
    volumes:
      - prometheus:/prometheus
    ports:
      - "9090:9090"
    links:
      - api:recipe-api
    depends_on:
      - api

  grafana:
    build: ./grafana
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    links:
      - prometheus
    depends_on:
      - prometheus

# The volumes are used to store the state across container instances
# i.e. so we don't lose metrics data if a container instance is destroyed and rebuilt
volumes:
  prometheus:
  grafana:
