#!/usr/bin/env bash
set -e

export AWS_PROFILE="recipes-deployer"
export AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id --profile ${AWS_PROFILE})
export AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key --profile ${AWS_PROFILE})

$(aws ecr get-login --no-include-email)

mvn clean deploy