#!/usr/bin/env bash
export AWS_PROFILE="recipe-api"
export AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id --profile ${AWS_PROFILE})
export AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key --profile ${AWS_PROFILE})

docker run -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
           -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
           -p 8080:8080 \
           -d 274158739358.dkr.ecr.eu-west-1.amazonaws.com/recipe-api