package com.blah.recipes.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.List;
import java.util.Objects;

@DynamoDBTable(tableName = "recipes")
public class Recipe {

    private String id;

    private String name;

    private List<Ingredient> ingredients;

    private Instructions instructions;

    public Recipe() {
    }

    public Recipe(String name, List<Ingredient> ingredients, Instructions instructions) {
        this.name = name;
        this.ingredients = ingredients;
        this.instructions = instructions;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "idx_global_name")
    public String getName() {
        return name;
    }

    @DynamoDBAttribute
    public List<Ingredient> getIngredients() {
        return ingredients;
    }

    @DynamoDBAttribute
    public Instructions getInstructions() {
        return instructions;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setIngredients(List<Ingredient> ingredients) {
        this.ingredients = ingredients;
    }

    public void setInstructions(Instructions instructions) {
        this.instructions = instructions;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Recipe recipe = (Recipe) o;
        return Objects.equals(name, recipe.name) &&
                Objects.equals(ingredients, recipe.ingredients) &&
                Objects.equals(instructions, recipe.instructions);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, ingredients, instructions);
    }

    @Override
    public String toString() {
        return "Recipe{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", ingredients=" + ingredients +
                ", instructions=" + instructions +
                '}';
    }
}
